# Generated by Django 3.2.25 on 2024-03-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('n_views', models.IntegerField()),
                ('genre', models.CharField(default='', max_length=20)),
                ('related_word_list', models.JSONField()),
                ('level', models.IntegerField(default=1)),
            ],
        ),
    ]
