# Generated by Django 3.2.25 on 2024-03-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_charactor_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactor',
            name='word',
        ),
    ]
