# Generated by Django 3.2.25 on 2024-03-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_alter_ranking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='user',
            field=models.CharField(max_length=256),
        ),
    ]
